<?xml version="1.0" encoding="utf-8"?>
<Database Name="moviereviews" Class="MovieReviewsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=moviereviews;Integrated Security=True" SettingsObjectName="LinqAndCSharp.Properties.Settings" SettingsPropertyName="moviereviewsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.movies" Member="Movies">
    <Type Name="Movie">
      <Column Name="movie_id" Member="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Member="Title" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="release_date" Member="ReleaseDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>